name: Terraform Linter 

on: 
  workflow_call: 
    inputs: 
      terraform-path: 
        required: false 
        default: "." 
        type: string 
      version: 
        required: false 
        default: latest 
        type: string

jobs:
  tflint: 
    runs-on: ubuntu-latest 
    timeout-minutes: 60 
    name: 'Terraform Linter' 
    steps: 
    - name: Checkout source code 
      uses: actions/checkout@v3
  
    - name: Download TF Lint 
      shell: bash 
      run: | 
        curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash 

    - name: Show version, Init and Run TFlint 
      run: | 
        tflint --version 
        tflint --init 
        tflint --chdir=${{ inputs.terraform-path }}