name: Terraform Docs

on:
  workflow_call:

jobs:
  terraform-docs:
    name: 'Terraform Docs'
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Terraform Docs
        uses: terraform-docs/gh-actions@v1.1.0
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          git-push: true
          git-commit-message: "GitHub Actions: terraform-docs automatic commit"
          template: |
            <!-- BEGIN_TF_DOCS -->
            {{ .Content }}
            <!-- END_TF_DOCS -->
