name: Terraform Docs 

on: 
  workflow_call:

jobs: 
  terraform-docs: 
    name: 'Terraform Docs' 
    runs-on: ubuntu-latest
    timeout-minutes: 10 

    steps: 
      - name: Git checkout 
        uses: actions/checkout@v3 
  
      - name: Generate docs 
        uses: terraform-docs/gh-actions@v1.0.0 
        with: 
          find-dir: . 
          output-file: README.md 
          git-push: true 
          git-commit-message: "GitHub Actions: terraform-docs automatic commit" 
          template: |- 
            <!-- BEGIN_TF_DOCS --> 
            # Usage 
            {{ .Content }} 
            <!-- END_TF_DOCS -->